http.host: 0.0.0.0
xpack.monitoring.elasticsearch.hosts:
- https://elasticsearch:9200
xpack.monitoring.elasticsearch.password: ${ELASTICSEARCH_PASSWORD}
xpack.monitoring.elasticsearch.ssl.certificate_authority: /usr/share/logstash/config/certs/ca/ca.crt
xpack.monitoring.elasticsearch.ssl.verification_mode: certificate
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.enabled: true
