services:
  backend:
    container_name: ft_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    user: "root"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/src:/app/src
      - db_data:/data
    env_file:
      - ./backend/.env
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - ft_transcendence

  database:
    container_name: ft_database
    build:
      context: ./database
      dockerfile: Dockerfile
    user: "root"
    ports:
      - "5001:8080"
    volumes:
      - db_data:/data
    restart: unless-stopped
    networks:
      - ft_transcendence

  frontend:
    container_name: ft_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    user: "root"
    working_dir: /app
    volumes:
      - ./frontend/game/:/app/game
      - front_build:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ft_transcendence

  nginx:
    container_name: ft_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "4000:443"
    volumes:
      - front_build:/usr/share/nginx/html
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
      - ft_transcendence

networks:
  ft_transcendence:
    driver: bridge

volumes:
  db_data:
  front_build: