services:
  backend:
    container_name: ft_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    user: "root"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - db_data:/data
    restart: unless-stopped
    networks:
      - ft_transcen

  database:
    container_name: ft_database
    build:
      context: ./database
      dockerfile: Dockerfile
    user: "root"
    ports:
      - "5000:8080"
    volumes:
      - db_data:/data
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ft_transcen

  frontend:
    container_name: ft_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    user: "root"
    working_dir: /app
    volumes:
      - front_build:/app/dist
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ft_transcen

  nginx:
    container_name: ft_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    volumes:
      - front_build:/usr/share/nginx/html
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
      - ft_transcen

networks:
  ft_transcen:
    driver: bridge

volumes:
  db_data:
  front_build:
